---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:verbose: true
:timeout: 10
development:
  :concurrency: 1
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [elasticsearch, 10]